name: flutter_filament_ffi
description: An FFI interface for the flutter_filament plugin (all platforms except web).
repository: https://github.com/nmfisher/flutter_filament/flutter_filament
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"
flutter:
  plugin:
    implements: flutter_filament_platform_interface
    platforms:
      ios:
        dartPluginClass: FlutterFilamentFFI
      android:
        dartPluginClass: FlutterFilamentFFI
      macos:
        dartPluginClass: FlutterFilamentFFI
      windows:
        dartPluginClass: FlutterFilamentFFI
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  flutter_filament_platform_interface:
    path: ../flutter_filament_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
