name: polyvox_filament
description: A Flutter plugin to wrap the Filament rendering engine.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.2
  plugin_platform_interface: ^2.0.0
  ffi: 
  tuple:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  ffigen: 

ffigen:
  output: 'lib/generated_bindings.dart'
  headers:
    entry-points:
      - 'ios/include/PolyvoxFilamentApi.h'

flutter:
  plugin:
    platforms:
      android:
        pluginClass: PolyvoxFilamentPlugin
        package: app.polyvox.filament
      ios:
        pluginClass: SwiftPolyvoxFilamentPlugin
      windows:
        pluginClass: PolyvoxFilamentPlugin
      linux:
        pluginClass: PolyvoxFilamentPlugin
