name: polyvox_filament
description: A Flutter plugin to wrap the Filament rendering engine.
version: 0.5.0
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0-0.2.pre"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  vector_math: ^2.1.2
  plugin_platform_interface: ^2.0.0
  tuple:
  ffi:
  wasm_ffi:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  ffigen: ^9.0.1

ffigen:
  output: 'lib/generated_bindings.dart'
  headers:
    entry-points:
      - 'ios/include/PolyvoxFilamentFFIApi.h'

flutter:
  plugin:
    platforms:
      android:
        pluginClass: PolyvoxFilamentPlugin
        package: app.polyvox.filament
      ios:
        pluginClass: SwiftPolyvoxFilamentPlugin
      macos:
        pluginClass: SwiftPolyvoxFilamentPlugin
      windows:
        pluginClass: PolyvoxFilamentPluginCApi
      linux:
        pluginClass: PolyvoxFilamentPlugin
      web:
        pluginClass: PolyvoxFilamentPluginWeb
        fileName: PolyvoxFilamentPluginWeb.dart
