name: polyvox_filament
description: A Flutter plugin to wrap the Filament rendering engine.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
    
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  plugin:
    platforms:
      android:
        pluginClass: PolyvoxFilamentPlugin
        package: app.polyvox.filament
      ios:
        pluginClass: PolyvoxFilamentPlugin
      windows:
        pluginClass: PolyvoxFilamentPlugin