name: flutter_filament_platform_interface
description: A common platform interface for the flutter_filament plugin.
repository: https://github.com/nmfisher/flutter_filament/flutter_filament
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  dart_filament:
    path: ../../dart_filament

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
