name: flutter_filament
description: A Flutter plugin to wrap the Filament rendering engine.
version: 0.7.0
homepage:

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.16.0-0.2.pre"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  vector_math: ^2.1.2
  plugin_platform_interface: ^2.0.0
  tuple:
  ffi:
  animation_tools_dart: ^0.0.4
  dart_filament:
    path: ../../dart_filament
  flutter_filament_platform_interface:
    path: ../flutter_filament_platform_interface
  flutter_filament_ffi:
    path: ../flutter_filament_ffi
  flutter_filament_web:
    path: ../flutter_filament_web


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  native_assets_cli: ^0.5.0
  native_toolchain_c: ^0.4.0

flutter:
  plugin:
    platforms:
      android:
        pluginClass: FlutterFilamentPlugin
        package: app.polyvox.filament
      ios:
        pluginClass: SwiftFlutterFilamentPlugin
      macos:
        pluginClass: SwiftFlutterFilamentPlugin
      windows:
        pluginClass: FlutterFilamentPluginCApi
      linux:
        pluginClass: FlutterFilamentPlugin
