name: PubDev Score

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  package-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # use this id to retrieve the outputs in the next steps
      # exit dirty when the package doesn't reach 100%
      - name: Check scores
        env:
          # "analysis" is the id set above
          # PERCENTAGE=$(( $TOTAL * 100 / $TOTAL_MAX ))
          TOTAL: ${{ steps.analysis.outputs.total }}
          TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
          JSON_OUT: ${{ steps.analysis.outputs.json_output }}
        run: |
          if (( $TOTAL != $TOTAL_MAX ))
          then
            echo There are missing points in the project!
            echo $TOTAL from $TOTAL_MAX Points reached
            echo $JSON_OUT | jq
            exit 1
          fi