name: thermion_dart
description: 3D rendering toolkit for Dart.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  vector_math: ^2.1.2
  plugin_platform_interface: ^2.0.0
  tuple:
  ffi:
  animation_tools_dart: ^0.0.4
  native_toolchain_c:
    git:
      url: git@github.com:nmfisher/native.git
      path: pkgs/native_toolchain_c
      ref: 99020084c4687be4c58c7115a167088c0441d1de
  archive: ^3.6.1

dev_dependencies:
  ffigen: ^11.0.0
  test:
