name: dart_filament
description: Dart bindings for the Filament Physically Based Renderer.
version: 0.5.0
homepage:

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  vector_math: ^2.1.2
  plugin_platform_interface: ^2.0.0
  tuple:
  ffi:
  animation_tools_dart:
    git:
      url: git@github.com:nmfisher/animation_tools_dart.git

dev_dependencies:
  ffigen: ^11.0.0
  native_assets_cli: ^0.5.0
  native_toolchain_c: ^0.4.0
  test:
