name: dart_filament
description: Dart bindings for the Filament Physically Based Renderer.
version: 0.5.0
homepage:

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  vector_math: ^2.1.2
  plugin_platform_interface: ^2.0.0
  tuple:
  ffi:
  animation_tools_dart: ^0.0.2

dev_dependencies:
  ffigen: ^11.0.0
  native_assets_cli: ^0.5.0
  native_toolchain_c: ^0.4.0
  test:

ffigen:
  output: 'lib/dart_filament/dart_filament.g.dart'
  headers:
    entry-points:
      - 'native/include/DartFilamentFFIApi.h'
      - 'native/include/DartFilamentApi.h'
    include-directives:
      - 'native/include/DartFilamentFFIApi.h'
      - 'native/include/DartFilamentApi.h'
  ffi-native:
    assetId: package:dart_filament/dart_filament.dart
