name: example_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-76.0.dev

# Add regular dependencies here.
dependencies:
  dart_filament:
    path: ../
  ffi:

dev_dependencies:
  ffigen: ^11.0.0
  lints: ^3.0.0
  test: ^1.24.0
  native_assets_cli: ^0.5.0
  native_toolchain_c: ^0.4.0
