name: thermion_flutter
description: A Flutter plugin to wrap the Filament rendering engine.
version: 0.7.0
homepage:

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.16.0-0.2.pre"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  vector_math: ^2.1.2
  plugin_platform_interface: ^2.0.0
  tuple:
  ffi:
  animation_tools_dart: ^0.0.4
  thermion_dart:
    path: ../../thermion_dart
  thermion_flutter_platform_interface:
    path: ../thermion_flutter_platform_interface
  thermion_flutter_ffi:
    path: ../thermion_flutter_ffi
  thermion_flutter_web:
    path: ../thermion_flutter_web


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        pluginClass: ThermionFlutterPlugin
        package: app.polyvox.filament
      ios:
        pluginClass: SwiftThermionFlutterPlugin
      macos:
        pluginClass: SwiftThermionFlutterPlugin
      windows:
        pluginClass: ThermionFlutterPluginCApi
      linux:
        pluginClass: ThermionFlutterPlugin
